"""Canonical Task abstractions."""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from fl_op.canonical.common import TimeInterval


class TaskRequirement(BaseModel):
    """A capability requirement a bundle must satisfy to perform a task."""

    model_config = ConfigDict(frozen=True)

    semantic_term: str
    operator: str  # gte, lte, eq, in, exists
    value: object


class MaterialRequirement(BaseModel):
    """A consumable requirement for a task."""

    model_config = ConfigDict(frozen=True)

    material_type: str
    quantity: float
    canonical_unit: str


class Task(BaseModel):
    """A unit of work requested by a farmer or generated by a contract."""

    model_config = ConfigDict(frozen=True)

    task_id: str
    order_id: str
    operation_type: str
    location_ref: str
    area_ha: Optional[float] = None
    # Generic work demand; preferred over area_ha for duration estimation when
    # present. The unit declares what the quantity counts (ha, m3, items, ...).
    work_quantity: Optional[float] = None
    work_quantity_unit: str = ""
    service_duration_minutes: Optional[int] = None
    # Mass the bundle must carry to the task (delivered material), in kg.
    load_demand_kg: Optional[float] = None
    time_windows: list[TimeInterval] = Field(default_factory=list)
    # Predecessor task that must be served before this one. A reference to a
    # task absent from the planning input is treated as already satisfied.
    depends_on_task_ref: Optional[str] = None
    deadline: Optional[datetime] = None
    priority_class: int = 5
    mandatory: bool = False
    requirements: list[TaskRequirement] = Field(default_factory=list)
    material_requirements: list[MaterialRequirement] = Field(default_factory=list)
    revenue_value_eur: float = 0.0
    penalty_per_day_eur: float = 0.0
    status: str = "pending"
    source_ref: str = ""
